from django.urls import path, re_path

from .views import render_frontend_page, serve_frontend_asset
from tracker import views as tracker_views


urlpatterns = [
    path("health", tracker_views.health_check),
    path("protected", tracker_views.protected_route),
    path("auth/login", tracker_views.login_view),
    path("auth/me", tracker_views.auth_me),
    path("users/register", tracker_views.register_user),
    path("users/login", tracker_views.login_view),
    path("users/me", tracker_views.user_me),
    path("users/", tracker_views.users_collection),
    path("users/promote/<int:user_id>", tracker_views.promote_user),
    path("users/<int:user_id>", tracker_views.delete_user),
    path("tasks/my-tasks", tracker_views.my_tasks),
    path("tasks/", tracker_views.tasks_collection),
    path("tasks/start/<int:task_id>", tracker_views.start_task),
    path("tasks/complete/<int:task_id>", tracker_views.complete_task),
    path("tasks/assign-task", tracker_views.assign_task),
    path("tasks/update/<int:task_id>", tracker_views.add_task_update),
    path("tasks/notifications", tracker_views.notifications_collection),
    path("tasks/notifications/read", tracker_views.mark_notifications_read),
    path("tasks/notifications/<int:notification_id>/read", tracker_views.mark_single_notification_read),
    path("tasks/my-dashboard", tracker_views.my_dashboard),
    path("tasks/<int:task_id>", tracker_views.task_detail),
    path("job-cards/", tracker_views.job_cards_collection),
    path("job-cards/open/<int:job_id>", tracker_views.open_job),
    path("job-cards/update/<int:job_id>", tracker_views.add_job_update),
    path("job-cards/close/<int:job_id>", tracker_views.close_job),
    path("job-cards/<int:job_id>", tracker_views.job_detail),
    path("analytics/total-hours", tracker_views.total_hours),
    path("analytics/weekly-summary", tracker_views.weekly_summary),
    path("analytics/leaderboard", tracker_views.leaderboard),
    path("analytics/whoami", tracker_views.whoami),
    path("analytics/productivity-score", tracker_views.productivity_score),
    path("analytics/my-charts", tracker_views.my_charts),
    path("analytics/dashboard", tracker_views.admin_dashboard),
    path("analytics/charts", tracker_views.analytics_charts),
    path("", lambda request: render_frontend_page(request, "index.html")),
    path("index.html", lambda request: render_frontend_page(request, "index.html")),
    path("login.html", lambda request: render_frontend_page(request, "login.html")),
    path("register.html", lambda request: render_frontend_page(request, "register.html")),
    path("dashboard.html", lambda request: render_frontend_page(request, "dashboard.html")),
    path("admin.html", lambda request: render_frontend_page(request, "admin.html")),
    re_path(r"^(?P<asset_path>(?:images/.+)|(?:.+\.(?:css|js|png|jpg|jpeg|gif|svg|webp|mp4)))$", serve_frontend_asset),
]
